import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import TextConverter from "../components/TextConverter/TextConverter";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Create a curl command for package installation in aem
        </h1>
        <video
          autoPlay
          loop
          controls
          style={{ width: "600px", height: "500px" }}
        >
          <source src="/Recorder.mp4" type="video/mp4" />
        </video>
        <TextConverter />
      </main>
      <hr />
      <footer className={styles.footer}>
        <div className="disclaimer">use at own risk</div>
        <div>kuckmc01</div>
      </footer>
    </div>
  );
}
